/**
 * Data Mapper Component Error Codes
 *
 * Following the unified error handling system guidelines:
 * Format: {COMPONENT}_{CATEGORY}_{SEQUENCE}
 * Component: DATA_MAPPER
 * Categories: VALIDATION (001-299), BUSINESS (300-599), SYSTEM (600-899), EXTERNAL (900-999)
 */

export const DATA_MAPPER_ERROR_CODES = {
  // 验证类错误 (001-299) - Validation Errors
  INVALID_RULE_ID_FORMAT: 'DATA_MAPPER_VALIDATION_001',
  INVALID_SUGGESTION_INDEX: 'DATA_MAPPER_VALIDATION_002',
  INVALID_MAPPING_RULE_DATA: 'DATA_MAPPER_VALIDATION_003',
  INVALID_FIELD_MAPPING: 'DATA_MAPPER_VALIDATION_004',
  INVALID_DATA_SOURCE_FORMAT: 'DATA_MAPPER_VALIDATION_005',
  MISSING_REQUIRED_FIELDS: 'DATA_MAPPER_VALIDATION_006',
  INVALID_PROVIDER_TYPE: 'DATA_MAPPER_VALIDATION_007',
  INVALID_API_TYPE: 'DATA_MAPPER_VALIDATION_008',
  MALFORMED_TEMPLATE_DATA: 'DATA_MAPPER_VALIDATION_009',
  INVALID_RULE_NAME: 'DATA_MAPPER_VALIDATION_010',

  // 业务逻辑错误 (300-599) - Business Logic Errors
  MAPPING_RULE_NOT_FOUND: 'DATA_MAPPER_BUSINESS_300',
  MAPPING_RULE_ALREADY_EXISTS: 'DATA_MAPPER_BUSINESS_301',
  RULE_APPLICATION_FAILED: 'DATA_MAPPER_BUSINESS_302',
  TEMPLATE_NOT_FOUND: 'DATA_MAPPER_BUSINESS_303',
  TEMPLATE_ALREADY_EXISTS: 'DATA_MAPPER_BUSINESS_304',
  RULE_CONFLICT: 'DATA_MAPPER_BUSINESS_305',
  TEMPLATE_GENERATION_FAILED: 'DATA_MAPPER_BUSINESS_306',
  RULE_ALIGNMENT_FAILED: 'DATA_MAPPER_BUSINESS_307',
  DATA_SOURCE_ANALYSIS_FAILED: 'DATA_MAPPER_BUSINESS_308',
  BEST_RULE_MATCH_FAILED: 'DATA_MAPPER_BUSINESS_309',
  RULE_DOCUMENT_CREATION_FAILED: 'DATA_MAPPER_BUSINESS_310',
  FLEXIBLE_MAPPING_FAILED: 'DATA_MAPPER_BUSINESS_311',

  // 系统资源错误 (600-899) - System Resource Errors
  RULE_CACHE_ERROR: 'DATA_MAPPER_SYSTEM_600',
  TEMPLATE_CACHE_ERROR: 'DATA_MAPPER_SYSTEM_601',
  MEMORY_PRESSURE_HIGH: 'DATA_MAPPER_SYSTEM_602',
  PROCESSING_TIMEOUT: 'DATA_MAPPER_SYSTEM_603',
  CONCURRENT_TASK_LIMIT_EXCEEDED: 'DATA_MAPPER_SYSTEM_604',
  RULE_SERIALIZATION_ERROR: 'DATA_MAPPER_SYSTEM_605',
  TEMPLATE_SERIALIZATION_ERROR: 'DATA_MAPPER_SYSTEM_606',
  ASYNC_TASK_LIMITER_ERROR: 'DATA_MAPPER_SYSTEM_607',

  // 外部依赖错误 (900-999) - External Dependency Errors
  DATABASE_CONNECTION_ERROR: 'DATA_MAPPER_EXTERNAL_900',
  MONGODB_QUERY_ERROR: 'DATA_MAPPER_EXTERNAL_901',
  REDIS_CACHE_ERROR: 'DATA_MAPPER_EXTERNAL_902',
  EVENT_BUS_ERROR: 'DATA_MAPPER_EXTERNAL_903',
  PAGINATION_SERVICE_ERROR: 'DATA_MAPPER_EXTERNAL_904',
  METRICS_COLLECTION_ERROR: 'DATA_MAPPER_EXTERNAL_905',
  EXTERNAL_TEMPLATE_FETCH_ERROR: 'DATA_MAPPER_EXTERNAL_906',
  RULE_DOCUMENT_FETCH_ERROR: 'DATA_MAPPER_EXTERNAL_907',
} as const;

export type DataMapperErrorCode = typeof DATA_MAPPER_ERROR_CODES[keyof typeof DATA_MAPPER_ERROR_CODES];