/**
 * 数据转换服务常量（精简版）
 * 仅保留当前模块实际使用的配置项
 */

import { NUMERIC_CONSTANTS } from "@common/constants/core";
import { HTTP_TIMEOUTS, BATCH_SIZE_SEMANTICS } from "@common/constants/semantic";

// 转换配置常量（被服务用于批量大小校验等）
export const DATATRANSFORM_CONFIG = Object.freeze({
  MAX_BATCH_SIZE: BATCH_SIZE_SEMANTICS.BASIC.MAX_SIZE,
  MAX_FIELD_MAPPINGS: 100,
  MAX_SAMPLE_SIZE: 10,
  DEFAULT_TIMEOUT_MS: HTTP_TIMEOUTS.REQUEST.NORMAL_MS,
  MAX_NESTED_DEPTH: 10,
  MAX_STRING_LENGTH: 10000,
  MAX_ARRAY_LENGTH: 10000,
} as const);

// 转换性能阈值常量（被服务用于慢转换日志分级）
export const DATATRANSFORM_PERFORMANCE_THRESHOLDS = Object.freeze({
  SLOW_TRANSFORMATION_MS: NUMERIC_CONSTANTS.N_1000,
  LARGE_DATASET_SIZE: BATCH_SIZE_SEMANTICS.BASIC.MAX_SIZE,
  HIGH_MEMORY_USAGE_MB: NUMERIC_CONSTANTS.N_100,
  MAX_PROCESSING_TIME_MS: NUMERIC_CONSTANTS.N_60000,
} as const);
