/**
 * Transformer Component Error Codes
 *
 * Following the unified error handling system guidelines:
 * Format: {COMPONENT}_{CATEGORY}_{SEQUENCE}
 * Component: TRANSFORMER
 * Categories: VALIDATION (001-299), BUSINESS (300-599), SYSTEM (600-899), EXTERNAL (900-999)
 */

export const TRANSFORMER_ERROR_CODES = Object.freeze({
  // 验证类错误 (001-299) - Validation Errors
  INVALID_REQUEST_DATA: 'TRANSFORMER_VALIDATION_001',
  MISSING_RAW_DATA: 'TRANSFORMER_VALIDATION_002',
  INVALID_PROVIDER: 'TRANSFORMER_VALIDATION_003',
  INVALID_RULE_TYPE: 'TRANSFORMER_VALIDATION_004',
  EMPTY_BATCH_REQUEST: 'TRANSFORMER_VALIDATION_005',
  BATCH_SIZE_EXCEEDED: 'TRANSFORMER_VALIDATION_006',
  INVALID_BATCH_FORMAT: 'TRANSFORMER_VALIDATION_007',
  INVALID_MAPPING_RULE_ID: 'TRANSFORMER_VALIDATION_008',
  INVALID_API_TYPE: 'TRANSFORMER_VALIDATION_009',
  MALFORMED_DATA_STRUCTURE: 'TRANSFORMER_VALIDATION_010',

  // 业务逻辑错误 (300-599) - Business Logic Errors
  NO_MAPPING_RULE_FOUND: 'TRANSFORMER_BUSINESS_300',
  TRANSFORMATION_FAILED: 'TRANSFORMER_BUSINESS_301',
  BATCH_TRANSFORMATION_FAILED: 'TRANSFORMER_BUSINESS_302',
  ALL_TRANSFORMATIONS_FAILED: 'TRANSFORMER_BUSINESS_303',
  RULE_APPLICATION_FAILED: 'TRANSFORMER_BUSINESS_304',
  DATA_COMPATIBILITY_FAILED: 'TRANSFORMER_BUSINESS_305',
  RULE_EXECUTION_FAILED: 'TRANSFORMER_BUSINESS_306',
  PARTIAL_TRANSFORMATION_SUCCESS: 'TRANSFORMER_BUSINESS_307',
  TRANSFORMATION_STATISTICS_ERROR: 'TRANSFORMER_BUSINESS_308',
  RULE_VALIDATION_FAILED: 'TRANSFORMER_BUSINESS_309',

  // 系统资源错误 (600-899) - System Resource Errors
  MAPPING_RULE_LOAD_ERROR: 'TRANSFORMER_SYSTEM_600',
  RULE_DOCUMENT_ERROR: 'TRANSFORMER_SYSTEM_601',
  PERFORMANCE_THRESHOLD_EXCEEDED: 'TRANSFORMER_SYSTEM_602',
  MEMORY_PRESSURE_HIGH: 'TRANSFORMER_SYSTEM_603',
  PROCESSING_TIMEOUT: 'TRANSFORMER_SYSTEM_604',
  BATCH_PROCESSING_OVERLOAD: 'TRANSFORMER_SYSTEM_605',
  RULE_CACHE_ERROR: 'TRANSFORMER_SYSTEM_606',
  STATISTICS_CALCULATION_ERROR: 'TRANSFORMER_SYSTEM_607',

  // 外部依赖错误 (900-999) - External Dependency Errors
  MAPPING_RULE_SERVICE_ERROR: 'TRANSFORMER_EXTERNAL_900',
  FLEXIBLE_MAPPING_SERVICE_ERROR: 'TRANSFORMER_EXTERNAL_901',
  RULE_STORAGE_ERROR: 'TRANSFORMER_EXTERNAL_902',
  EVENT_BUS_ERROR: 'TRANSFORMER_EXTERNAL_903',
  METRICS_COLLECTION_ERROR: 'TRANSFORMER_EXTERNAL_904',
  DATABASE_CONNECTION_ERROR: 'TRANSFORMER_EXTERNAL_905',
  EXTERNAL_RULE_FETCH_ERROR: 'TRANSFORMER_EXTERNAL_906',
});

export type TransformerErrorCode =
  typeof TRANSFORMER_ERROR_CODES[keyof typeof TRANSFORMER_ERROR_CODES];