/**
 * DATA_FETCHER компонент - константы кодов ошибок
 */

import { deepFreeze } from '@common/utils/object-immutability.util';

export const DATA_FETCHER_ERROR_CODES = deepFreeze({
  // Валидационные ошибки (001-299)
  MISSING_REQUIRED_PARAMS: 'DATA_FETCHER_VALIDATION_001',
  INVALID_SYMBOLS: 'DATA_FETCHER_VALIDATION_002',
  SYMBOLS_LIMIT_EXCEEDED: 'DATA_FETCHER_VALIDATION_003',
  INVALID_PROVIDER: 'DATA_FETCHER_VALIDATION_004',
  INVALID_CAPABILITY: 'DATA_FETCHER_VALIDATION_005',

  // Бизнес-логика ошибки (300-599)
  CAPABILITY_NOT_SUPPORTED: 'DATA_FETCHER_BUSINESS_300',
  PROVIDER_NOT_FOUND: 'DATA_FETCHER_BUSINESS_301',
  CONTEXT_SERVICE_NOT_AVAILABLE: 'DATA_FETCHER_BUSINESS_302',
  DATA_FETCH_FAILED: 'DATA_FETCHER_BUSINESS_303',
  PARTIAL_FAILURE: 'DATA_FETCHER_BUSINESS_304',

  // Системные ошибки (600-899)
  EXECUTION_TIMEOUT: 'DATA_FETCHER_SYSTEM_600',
  MEMORY_PRESSURE: 'DATA_FETCHER_SYSTEM_601',
  CPU_OVERLOAD: 'DATA_FETCHER_SYSTEM_602',

  // Ошибки внешних зависимостей (900-999)
  PROVIDER_UNAVAILABLE: 'DATA_FETCHER_EXTERNAL_900',
  PROVIDER_RATE_LIMITED: 'DATA_FETCHER_EXTERNAL_901',
  NETWORK_ERROR: 'DATA_FETCHER_EXTERNAL_902',
}); 