/**
 * Data Mapper Cache Error Codes
 * Коды ошибок для компонента кэширования правил маппинга данных
 */
export const DATA_MAPPER_CACHE_ERROR_CODES = {
  // Validation errors (001-299)
  INVALID_RULE_ID: 'DATA_MAPPER_CACHE_VALIDATION_001',
  INVALID_KEY_FORMAT: 'DATA_MAPPER_CACHE_VALIDATION_002',
  KEY_LENGTH_EXCEEDED: 'DATA_MAPPER_CACHE_VALIDATION_003',
  RULE_TOO_LARGE: 'DATA_MAPPER_CACHE_VALIDATION_004',
  INVALID_PROVIDER: 'DATA_MAPPER_CACHE_VALIDATION_005',
  INVALID_API_TYPE: 'DATA_MAPPER_CACHE_VALIDATION_006',
  INVALID_RULE_TYPE: 'DATA_MAPPER_CACHE_VALIDATION_007',
  
  // Business logic errors (300-599)
  RULE_NOT_FOUND: 'DATA_MAPPER_CACHE_BUSINESS_300',
  BEST_RULE_NOT_FOUND: 'DATA_MAPPER_CACHE_BUSINESS_301',
  PROVIDER_RULES_NOT_FOUND: 'DATA_MAPPER_CACHE_BUSINESS_302',
  DUPLICATE_RULE_ID: 'DATA_MAPPER_CACHE_BUSINESS_303',
  
  // System resource errors (600-899)
  MEMORY_PRESSURE: 'DATA_MAPPER_CACHE_SYSTEM_600',
  OPERATION_TIMEOUT: 'DATA_MAPPER_CACHE_SYSTEM_700',
  SCAN_OPERATION_TIMEOUT: 'DATA_MAPPER_CACHE_SYSTEM_701',
  
  // External dependency errors (900-999)
  REDIS_CONNECTION_ERROR: 'DATA_MAPPER_CACHE_EXTERNAL_900',
  REDIS_OPERATION_FAILED: 'DATA_MAPPER_CACHE_EXTERNAL_901',
  CACHE_SET_FAILED: 'DATA_MAPPER_CACHE_EXTERNAL_902',
  CACHE_GET_FAILED: 'DATA_MAPPER_CACHE_EXTERNAL_903',
  CACHE_DELETE_FAILED: 'DATA_MAPPER_CACHE_EXTERNAL_904',
} as const; 