/**
 * Notification Component Error Codes
 *
 * Following the unified error handling system guidelines:
 * Format: {COMPONENT}_{CATEGORY}_{SEQUENCE}
 * Component: NOTIFICATION
 * Categories: VALIDATION (001-299), BUSINESS (300-599), SYSTEM (600-899), EXTERNAL (900-999)
 */

export const NOTIFICATION_ERROR_CODES = {
  // 验证类错误 (001-299) - Validation Errors
  CONFIG_NOT_FOUND: 'NOTIFICATION_VALIDATION_001',
  INVALID_CHANNEL_TYPE: 'NOTIFICATION_VALIDATION_002',
  UNSUPPORTED_CHANNEL_TYPE: 'NOTIFICATION_VALIDATION_003',
  INVALID_TEMPLATE_DATA: 'NOTIFICATION_VALIDATION_004',
  INVALID_NOTIFICATION_REQUEST: 'NOTIFICATION_VALIDATION_005',
  INVALID_CHANNEL_CONFIG: 'NOTIFICATION_VALIDATION_006',
  MISSING_REQUIRED_FIELDS: 'NOTIFICATION_VALIDATION_007',
  TEMPLATE_VALIDATION_FAILED: 'NOTIFICATION_VALIDATION_008',
  CHANNEL_VALIDATION_FAILED: 'NOTIFICATION_VALIDATION_009',
  CONFIGURATION_VALIDATION_FAILED: 'NOTIFICATION_VALIDATION_010',

  // 业务逻辑错误 (300-599) - Business Logic Errors
  SEND_NOTIFICATION_FAILED: 'NOTIFICATION_BUSINESS_300',
  RESOLVE_NOTIFICATION_FAILED: 'NOTIFICATION_BUSINESS_301',
  CONFIRM_NOTIFICATION_FAILED: 'NOTIFICATION_BUSINESS_302',
  SUPPRESS_NOTIFICATION_FAILED: 'NOTIFICATION_BUSINESS_303',
  ESCALATE_NOTIFICATION_FAILED: 'NOTIFICATION_BUSINESS_304',
  TEMPLATE_RENDERING_FAILED: 'NOTIFICATION_BUSINESS_305',
  CHANNEL_SEND_FAILED: 'NOTIFICATION_BUSINESS_306',
  NOTIFICATION_THROTTLED: 'NOTIFICATION_BUSINESS_307',
  DUPLICATE_NOTIFICATION: 'NOTIFICATION_BUSINESS_308',
  NOTIFICATION_EXPIRED: 'NOTIFICATION_BUSINESS_309',

  // 系统资源错误 (600-899) - System Resource Errors
  TEMPLATE_ENGINE_ERROR: 'NOTIFICATION_SYSTEM_600',
  TEMPLATE_COMPILATION_ERROR: 'NOTIFICATION_SYSTEM_601',
  MEMORY_PRESSURE_HIGH: 'NOTIFICATION_SYSTEM_602',
  QUEUE_CAPACITY_EXCEEDED: 'NOTIFICATION_SYSTEM_603',
  RATE_LIMIT_EXCEEDED: 'NOTIFICATION_SYSTEM_604',
  TEMPLATE_CACHE_ERROR: 'NOTIFICATION_SYSTEM_605',
  HANDLER_INITIALIZATION_ERROR: 'NOTIFICATION_SYSTEM_606',

  // 外部依赖错误 (900-999) - External Dependency Errors
  EMAIL_SERVICE_UNAVAILABLE: 'NOTIFICATION_EXTERNAL_900',
  SLACK_API_ERROR: 'NOTIFICATION_EXTERNAL_901',
  WEBHOOK_DELIVERY_FAILED: 'NOTIFICATION_EXTERNAL_902',
  DINGTALK_API_ERROR: 'NOTIFICATION_EXTERNAL_903',
  SMS_SERVICE_ERROR: 'NOTIFICATION_EXTERNAL_904',
  DATABASE_ERROR: 'NOTIFICATION_EXTERNAL_905',
  TEMPLATE_STORAGE_ERROR: 'NOTIFICATION_EXTERNAL_950',
  CONFIG_SERVICE_ERROR: 'NOTIFICATION_EXTERNAL_951',
  EVENT_BUS_ERROR: 'NOTIFICATION_EXTERNAL_952',
} as const;

export type NotificationErrorCode = typeof NOTIFICATION_ERROR_CODES[keyof typeof NOTIFICATION_ERROR_CODES];