/**
 * Smart Cache 环境变量键名常量
 * 采用类型安全的方式管理环境变量键名，提供编译时检查
 */
export const SMART_CACHE_ENV_VARS = Object.freeze({
  // 基础配置 - 解决30个分散环境变量键名问题
  MIN_UPDATE_INTERVAL_MS: "SMART_CACHE_MIN_UPDATE_INTERVAL_MS",
  MAX_CONCURRENT_UPDATES: "SMART_CACHE_MAX_CONCURRENT_UPDATES",
  SHUTDOWN_TIMEOUT_MS: "SMART_CACHE_SHUTDOWN_TIMEOUT_MS",

  // TTL策略配置 - 明确单位为秒
  STRONG_TTL_SECONDS: "CACHE_STRONG_TTL_SECONDS",
  WEAK_TTL_SECONDS: "CACHE_WEAK_TTL_SECONDS",
  MARKET_AWARE_TTL_SECONDS: "CACHE_MARKET_AWARE_TTL_SECONDS",
  ADAPTIVE_TTL_BASE_SECONDS: "CACHE_ADAPTIVE_TTL_BASE_SECONDS",
  ADAPTIVE_TTL_MIN_SECONDS: "CACHE_ADAPTIVE_TTL_MIN_SECONDS",
  ADAPTIVE_TTL_MAX_SECONDS: "CACHE_ADAPTIVE_TTL_MAX_SECONDS",

  // 性能阈值配置 - 明确表示比例
  MEMORY_PRESSURE_THRESHOLD_RATIO:
    "SMART_CACHE_MEMORY_PRESSURE_THRESHOLD_RATIO",
  CPU_PRESSURE_THRESHOLD_RATIO: "SMART_CACHE_CPU_PRESSURE_THRESHOLD_RATIO",
  CACHE_HIT_RATE_TARGET: "SMART_CACHE_HIT_RATE_TARGET",

  // 批处理配置 - 明确数量单位
  DEFAULT_BATCH_SIZE_COUNT: "SMART_CACHE_DEFAULT_BATCH_SIZE_COUNT",
  MAX_BATCH_SIZE_COUNT: "SMART_CACHE_MAX_BATCH_SIZE_COUNT",
  MIN_BATCH_SIZE_COUNT: "SMART_CACHE_MIN_BATCH_SIZE_COUNT",

  // 监控配置 - 布尔值和间隔时间
  ENABLE_METRICS: "SMART_CACHE_ENABLE_METRICS",
  METRICS_COLLECTION_INTERVAL_MS: "SMART_CACHE_METRICS_COLLECTION_INTERVAL_MS",
  ENABLE_BACKGROUND_UPDATE: "SMART_CACHE_ENABLE_BACKGROUND_UPDATE",
  ENABLE_DATA_CHANGE_DETECTION: "SMART_CACHE_ENABLE_DATA_CHANGE_DETECTION",
  HEALTH_CHECK_INTERVAL_MS: "SMART_CACHE_HEALTH_CHECK_INTERVAL_MS",

  // 内存管理配置
  MIN_MEMORY_MB: "SMART_CACHE_MIN_MEMORY_MB",
  MAX_CACHE_SIZE_MB: "SMART_CACHE_MAX_CACHE_SIZE_MB",

  // 更新阈值比例配置
  STRONG_UPDATE_RATIO: "CACHE_STRONG_UPDATE_RATIO",
  WEAK_UPDATE_RATIO: "CACHE_WEAK_UPDATE_RATIO",
  MARKET_OPEN_UPDATE_RATIO: "CACHE_MARKET_OPEN_UPDATE_RATIO",
  MARKET_CLOSED_UPDATE_RATIO: "CACHE_MARKET_CLOSED_UPDATE_RATIO",

  // 其他策略配置
  ENABLE_ADAPTIVE_STRATEGY: "SMART_CACHE_ENABLE_ADAPTIVE_STRATEGY",
  ENABLE_MARKET_AWARE_STRATEGY: "SMART_CACHE_ENABLE_MARKET_AWARE_STRATEGY",
} as const);

// 类型推导：环境变量键名类型
export type SmartCacheEnvVarKey =
  (typeof SMART_CACHE_ENV_VARS)[keyof typeof SMART_CACHE_ENV_VARS];

// 环境变量配置项类型映射
export type SmartCacheEnvConfig = {
  readonly [K in keyof typeof SMART_CACHE_ENV_VARS]: string;
};

// 提供类型安全的环境变量访问器
export const getEnvVar = <K extends keyof typeof SMART_CACHE_ENV_VARS>(
  key: K,
): SmartCacheEnvVarKey => SMART_CACHE_ENV_VARS[key];
