import {
  CACHE_CORE_VALUES,
  CACHE_CORE_TTL,
  CACHE_CORE_BATCH_SIZES,
} from '../../../foundation/constants/core-values.constants';

/**
 * Smart Cache 常量定义
 * 采用描述性命名，明确单位和语义
 * 使用Common-cache的共享常量作为基础，同时保持向后兼容性
 */
export const SMART_CACHE_CONSTANTS = Object.freeze({
  // 最小TTL集合（秒）
  TTL: {
    STRONG_TIMELINESS_DEFAULT_S: CACHE_CORE_TTL.REAL_TIME_TTL_SECONDS,
    WEAK_TIMELINESS_DEFAULT_S: CACHE_CORE_TTL.BATCH_QUERY_TTL_SECONDS,
    MARKET_OPEN_DEFAULT_S: CACHE_CORE_TTL.TRADING_HOURS_TTL_SECONDS,
    MARKET_CLOSED_DEFAULT_S: CACHE_CORE_TTL.OFF_HOURS_TTL_SECONDS,
    ADAPTIVE_MAX_S: CACHE_CORE_TTL.ARCHIVE_TTL_SECONDS,
  },

  // 并发控制（最小集合）
  CONCURRENCY_LIMITS: {
    MIN_CONCURRENT_UPDATES_COUNT: CACHE_CORE_VALUES.MIN_CONCURRENT_OPERATIONS,
    MAX_CONCURRENT_UPDATES_COUNT: CACHE_CORE_VALUES.MAX_CONCURRENT_OPERATIONS,
    DEFAULT_BATCH_SIZE_COUNT: CACHE_CORE_BATCH_SIZES.MEDIUM_BATCH_SIZE,
  },
} as const); // 使用 as const 提供更严格的类型推导

// 深度冻结所有嵌套对象以确保完全不可变性
Object.freeze(SMART_CACHE_CONSTANTS.TTL);
Object.freeze(SMART_CACHE_CONSTANTS.CONCURRENCY_LIMITS);

// 从常量对象推导类型，提高类型安全性
export type SmartCacheConstantsType = typeof SMART_CACHE_CONSTANTS;
export type TTLType = typeof SMART_CACHE_CONSTANTS.TTL;
export type ConcurrencyLimitsType = typeof SMART_CACHE_CONSTANTS.CONCURRENCY_LIMITS;
