/**
 * Smart Cache Component Error Codes
 *
 * Following the unified error handling system guidelines:
 * Format: {COMPONENT}_{CATEGORY}_{SEQUENCE}
 * Component: SMART_CACHE
 * Categories: VALIDATION (001-299), BUSINESS (300-599), SYSTEM (600-899), EXTERNAL (900-999)
 */

export const SMART_CACHE_ERROR_CODES = {
  // 验证类错误 (001-299) - Validation Errors
  MISSING_CACHE_KEY_PREFIX: 'SMART_CACHE_VALIDATION_001',
  EMPTY_SYMBOLS_LIST: 'SMART_CACHE_VALIDATION_002',
  INVALID_CACHE_KEY_FORMAT: 'SMART_CACHE_VALIDATION_003',
  EMPTY_VALID_SYMBOLS: 'SMART_CACHE_VALIDATION_004',
  CRYPTO_MODULE_UNAVAILABLE: 'SMART_CACHE_VALIDATION_005',
  CONFIG_VALIDATION_FAILED: 'SMART_CACHE_VALIDATION_006',
  INVALID_STRATEGY_CONFIG: 'SMART_CACHE_VALIDATION_007',
  INVALID_TTL_CONFIGURATION: 'SMART_CACHE_VALIDATION_008',

  // 业务逻辑错误 (300-599) - Business Logic Errors
  CACHE_STRATEGY_NOT_SUPPORTED: 'SMART_CACHE_BUSINESS_300',
  CACHE_UPDATE_CONFLICT: 'SMART_CACHE_BUSINESS_301',
  BACKGROUND_UPDATE_DISABLED: 'SMART_CACHE_BUSINESS_302',
  CACHE_ORCHESTRATION_FAILED: 'SMART_CACHE_BUSINESS_303',
  PERFORMANCE_OPTIMIZATION_FAILED: 'SMART_CACHE_BUSINESS_304',
  MARKET_INFERENCE_FAILED: 'SMART_CACHE_BUSINESS_305',

  // 系统资源错误 (600-899) - System Resource Errors
  MEMORY_PRESSURE_HIGH: 'SMART_CACHE_SYSTEM_600',
  CONCURRENCY_LIMIT_EXCEEDED: 'SMART_CACHE_SYSTEM_601',
  CLEANUP_OPERATION_TIMEOUT: 'SMART_CACHE_SYSTEM_700',
  BACKGROUND_TASK_TIMEOUT: 'SMART_CACHE_SYSTEM_701',
  RESOURCE_CLEANUP_FAILED: 'SMART_CACHE_SYSTEM_702',
  TIMER_MANAGEMENT_ERROR: 'SMART_CACHE_SYSTEM_703',

  // 外部依赖错误 (900-999) - External Dependency Errors
  CACHE_SERVICE_UNAVAILABLE: 'SMART_CACHE_EXTERNAL_900',
  STORAGE_SERVICE_ERROR: 'SMART_CACHE_EXTERNAL_901',
} as const;

export type SmartCacheErrorCode = typeof SMART_CACHE_ERROR_CODES[keyof typeof SMART_CACHE_ERROR_CODES];
