/**
 * Symbol Mapper组件错误码常量定义
 *
 * 错误码格式：SYMBOL_MAPPER_{CATEGORY}_{SEQUENCE}
 * - VALIDATION: 验证类错误 (001-299)
 * - BUSINESS: 业务逻辑错误 (300-599)
 * - SYSTEM: 系统资源错误 (600-899)
 * - EXTERNAL: 外部依赖错误 (900-999)
 */

export const SYMBOL_MAPPER_ERROR_CODES = Object.freeze({
  // ==================== 验证类错误 (001-299) ====================

  // 符号验证 (001-099)
  INVALID_SYMBOL_FORMAT: 'SYMBOL_MAPPER_VALIDATION_001',
  MISSING_SYMBOL_PARAM: 'SYMBOL_MAPPER_VALIDATION_002',
  SYMBOL_LENGTH_EXCEEDED: 'SYMBOL_MAPPER_VALIDATION_003',
  INVALID_SYMBOL_CHARACTERS: 'SYMBOL_MAPPER_VALIDATION_004',
  DUPLICATE_SYMBOLS: 'SYMBOL_MAPPER_VALIDATION_005',
  SYMBOLS_LIMIT_EXCEEDED: 'SYMBOL_MAPPER_VALIDATION_006',
  EMPTY_SYMBOLS_ARRAY: 'SYMBOL_MAPPER_VALIDATION_007',
  UNSUPPORTED_SYMBOL_TYPE: 'SYMBOL_MAPPER_VALIDATION_008',

  // 数据源验证 (100-199)
  INVALID_DATA_SOURCE_NAME: 'SYMBOL_MAPPER_VALIDATION_100',
  MISSING_DATA_SOURCE_PARAM: 'SYMBOL_MAPPER_VALIDATION_101',
  UNSUPPORTED_DATA_SOURCE: 'SYMBOL_MAPPER_VALIDATION_102',
  DATA_SOURCE_NAME_TOO_LONG: 'SYMBOL_MAPPER_VALIDATION_103',
  INVALID_PROVIDER_FORMAT: 'SYMBOL_MAPPER_VALIDATION_104',
  MISSING_PROVIDER_CONFIG: 'SYMBOL_MAPPER_VALIDATION_105',

  // 映射规则验证 (200-299)
  INVALID_MAPPING_RULE: 'SYMBOL_MAPPER_VALIDATION_200',
  MALFORMED_MAPPING_PATTERN: 'SYMBOL_MAPPER_VALIDATION_201',
  MISSING_MAPPING_FIELDS: 'SYMBOL_MAPPER_VALIDATION_202',
  INVALID_MAPPING_PRIORITY: 'SYMBOL_MAPPER_VALIDATION_203',
  CONFLICTING_MAPPING_RULES: 'SYMBOL_MAPPER_VALIDATION_205',

  // ==================== 业务逻辑错误 (300-599) ====================

  // 映射配置错误 (300-399)
  MAPPING_CONFIG_NOT_FOUND: 'SYMBOL_MAPPER_BUSINESS_300',
  MAPPING_CONFIG_ALREADY_EXISTS: 'SYMBOL_MAPPER_BUSINESS_301',
  MAPPING_CONFIG_IN_USE: 'SYMBOL_MAPPER_BUSINESS_302',
  MAPPING_CONFIG_DISABLED: 'SYMBOL_MAPPER_BUSINESS_303',
  MAPPING_CONFIG_CORRUPTED: 'SYMBOL_MAPPER_BUSINESS_304',
  MAPPING_CONFIG_VERSION_MISMATCH: 'SYMBOL_MAPPER_BUSINESS_305',
  CIRCULAR_MAPPING_DETECTED: 'SYMBOL_MAPPER_BUSINESS_306',

  // 数据源错误 (400-499)
  DATA_SOURCE_NOT_FOUND: 'SYMBOL_MAPPER_BUSINESS_400',
  DATA_SOURCE_MAPPING_NOT_FOUND: 'SYMBOL_MAPPER_BUSINESS_401',
  DATA_SOURCE_UNAVAILABLE: 'SYMBOL_MAPPER_BUSINESS_402',
  DATA_SOURCE_AUTHENTICATION_FAILED: 'SYMBOL_MAPPER_BUSINESS_403',
  DATA_SOURCE_RATE_LIMITED: 'SYMBOL_MAPPER_BUSINESS_404',
  DATA_SOURCE_FORMAT_CHANGED: 'SYMBOL_MAPPER_BUSINESS_405',

  // 映射操作错误 (500-599)
  SYMBOL_MAPPING_FAILED: 'SYMBOL_MAPPER_BUSINESS_500',
  MAPPING_RULE_NOT_FOUND: 'SYMBOL_MAPPER_BUSINESS_501',
  MAPPING_RESULT_EMPTY: 'SYMBOL_MAPPER_BUSINESS_502',
  MAPPING_CONFLICT_DETECTED: 'SYMBOL_MAPPER_BUSINESS_503',
  BATCH_MAPPING_FAILED: 'SYMBOL_MAPPER_BUSINESS_504',
  MAPPING_RULE_EXECUTION_FAILED: 'SYMBOL_MAPPER_BUSINESS_505',
  SYMBOL_TRANSFORMATION_FAILED: 'SYMBOL_MAPPER_BUSINESS_506',

  // ==================== 系统资源错误 (600-899) ====================

  // 缓存错误 (600-699)
  CACHE_OPERATION_FAILED: 'SYMBOL_MAPPER_SYSTEM_600',
  CACHE_MISS_CRITICAL: 'SYMBOL_MAPPER_SYSTEM_601',
  CACHE_INVALIDATION_FAILED: 'SYMBOL_MAPPER_SYSTEM_602',
  CACHE_WARMING_FAILED: 'SYMBOL_MAPPER_SYSTEM_603',
  CACHE_MEMORY_PRESSURE: 'SYMBOL_MAPPER_SYSTEM_604',
  LRU_CACHE_OVERFLOW: 'SYMBOL_MAPPER_SYSTEM_605',

  // 性能和资源 (700-799)
  MEMORY_LIMIT_EXCEEDED: 'SYMBOL_MAPPER_SYSTEM_700',
  CPU_OVERLOAD: 'SYMBOL_MAPPER_SYSTEM_701',
  PROCESSING_TIMEOUT: 'SYMBOL_MAPPER_SYSTEM_702',
  CONCURRENT_OPERATIONS_LIMIT: 'SYMBOL_MAPPER_SYSTEM_703',
  THREAD_POOL_EXHAUSTED: 'SYMBOL_MAPPER_SYSTEM_704',
  RESOURCE_CONTENTION: 'SYMBOL_MAPPER_SYSTEM_705',

  // 配置和环境 (800-899)
  SERVICE_INITIALIZATION_FAILED: 'SYMBOL_MAPPER_SYSTEM_800',
  CONFIGURATION_RELOAD_FAILED: 'SYMBOL_MAPPER_SYSTEM_801',
  HEALTH_CHECK_FAILED: 'SYMBOL_MAPPER_SYSTEM_802',
  MONITORING_UNAVAILABLE: 'SYMBOL_MAPPER_SYSTEM_803',
  RULE_ENGINE_STARTUP_FAILED: 'SYMBOL_MAPPER_SYSTEM_804',

  // ==================== 外部依赖错误 (900-999) ====================

  // 数据库错误 (900-929)
  DATABASE_CONNECTION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_900',
  DATABASE_OPERATION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_901',
  DATABASE_TRANSACTION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_902',
  DATABASE_CONSTRAINT_VIOLATION: 'SYMBOL_MAPPER_EXTERNAL_903',
  DATABASE_TIMEOUT: 'SYMBOL_MAPPER_EXTERNAL_904',
  MONGODB_AGGREGATION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_905',

  // 缓存服务错误 (930-949)
  REDIS_CONNECTION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_930',
  REDIS_OPERATION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_931',
  CACHE_SERVICE_UNAVAILABLE: 'SYMBOL_MAPPER_EXTERNAL_932',
  CACHE_SERIALIZATION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_933',

  // 外部API错误 (950-979)
  EXTERNAL_API_ERROR: 'SYMBOL_MAPPER_EXTERNAL_950',
  PROVIDER_API_UNAVAILABLE: 'SYMBOL_MAPPER_EXTERNAL_951',
  PROVIDER_AUTHENTICATION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_952',
  PROVIDER_RATE_LIMITED: 'SYMBOL_MAPPER_EXTERNAL_953',
  PROVIDER_DATA_FORMAT_ERROR: 'SYMBOL_MAPPER_EXTERNAL_954',

  // 网络和基础设施 (980-999)
  NETWORK_CONNECTION_ERROR: 'SYMBOL_MAPPER_EXTERNAL_980',
  NETWORK_TIMEOUT: 'SYMBOL_MAPPER_EXTERNAL_981',
  DNS_RESOLUTION_FAILED: 'SYMBOL_MAPPER_EXTERNAL_982',
  SSL_CERTIFICATE_ERROR: 'SYMBOL_MAPPER_EXTERNAL_983',
  INFRASTRUCTURE_FAILURE: 'SYMBOL_MAPPER_EXTERNAL_984',
});

// 错误码类型定义
export type SymbolMapperErrorCode = (typeof SYMBOL_MAPPER_ERROR_CODES)[keyof typeof SYMBOL_MAPPER_ERROR_CODES];

// 定义需要特殊处理的错误码集合，提高代码可读性和可维护性
const RETRYABLE_SYSTEM_CODES = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.PROCESSING_TIMEOUT,
  SYMBOL_MAPPER_ERROR_CODES.CPU_OVERLOAD,
  SYMBOL_MAPPER_ERROR_CODES.CACHE_MEMORY_PRESSURE,
  SYMBOL_MAPPER_ERROR_CODES.THREAD_POOL_EXHAUSTED,
  SYMBOL_MAPPER_ERROR_CODES.RESOURCE_CONTENTION,
  SYMBOL_MAPPER_ERROR_CODES.CACHE_OPERATION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.CACHE_MISS_CRITICAL,
]);

const RETRYABLE_BUSINESS_CODES = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.SYMBOL_MAPPING_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.MAPPING_RULE_EXECUTION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.DATA_SOURCE_UNAVAILABLE,
]);

const NON_RETRYABLE_EXTERNAL_CODES = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.PROVIDER_AUTHENTICATION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.PROVIDER_DATA_FORMAT_ERROR,
  SYMBOL_MAPPER_ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION,
]);

const HIGH_SEVERITY_BUSINESS_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_CORRUPTED,
  SYMBOL_MAPPER_ERROR_CODES.CIRCULAR_MAPPING_DETECTED,
  SYMBOL_MAPPER_ERROR_CODES.DATA_SOURCE_AUTHENTICATION_FAILED,
]);

const CRITICAL_SYSTEM_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.MEMORY_LIMIT_EXCEEDED,
  SYMBOL_MAPPER_ERROR_CODES.SERVICE_INITIALIZATION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.RULE_ENGINE_STARTUP_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.CPU_OVERLOAD,
]);

const CRITICAL_EXTERNAL_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.DATABASE_CONNECTION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.INFRASTRUCTURE_FAILURE,
  SYMBOL_MAPPER_ERROR_CODES.MONGODB_AGGREGATION_FAILED,
]);

const CACHE_CLEANUP_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.CACHE_MEMORY_PRESSURE,
  SYMBOL_MAPPER_ERROR_CODES.LRU_CACHE_OVERFLOW,
  SYMBOL_MAPPER_ERROR_CODES.CACHE_INVALIDATION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_CORRUPTED,
]);

const RULE_RELOAD_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_CORRUPTED,
  SYMBOL_MAPPER_ERROR_CODES.RULE_ENGINE_STARTUP_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_VERSION_MISMATCH,
  SYMBOL_MAPPER_ERROR_CODES.CONFIGURATION_RELOAD_FAILED,
]);

const SERVICE_DEGRADATION_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.DATABASE_CONNECTION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.CACHE_SERVICE_UNAVAILABLE,
  SYMBOL_MAPPER_ERROR_CODES.MEMORY_LIMIT_EXCEEDED,
  SYMBOL_MAPPER_ERROR_CODES.CPU_OVERLOAD,
  SYMBOL_MAPPER_ERROR_CODES.INFRASTRUCTURE_FAILURE,
]);

const IMMEDIATE_ALERT_ERRORS = new Set<SymbolMapperErrorCode>([
  SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_CORRUPTED,
  SYMBOL_MAPPER_ERROR_CODES.SERVICE_INITIALIZATION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.DATABASE_CONNECTION_FAILED,
  SYMBOL_MAPPER_ERROR_CODES.INFRASTRUCTURE_FAILURE,
  SYMBOL_MAPPER_ERROR_CODES.CIRCULAR_MAPPING_DETECTED,
]);

// 错误分类辅助函数
export const SymbolMapperErrorCategories = {
  /**
   * 判断是否为验证类错误
   */
  isValidationError: (errorCode: SymbolMapperErrorCode): boolean => {
    return errorCode.startsWith('SYMBOL_MAPPER_VALIDATION');
  },

  /**
   * 判断是否为业务逻辑错误
   */
  isBusinessError: (errorCode: SymbolMapperErrorCode): boolean => {
    return errorCode.startsWith('SYMBOL_MAPPER_BUSINESS');
  },

  /**
   * 判断是否为系统资源错误
   */
  isSystemError: (errorCode: SymbolMapperErrorCode): boolean => {
    return errorCode.startsWith('SYMBOL_MAPPER_SYSTEM');
  },

  /**
   * 判断是否为外部依赖错误
   */
  isExternalError: (errorCode: SymbolMapperErrorCode): boolean => {
    return errorCode.startsWith('SYMBOL_MAPPER_EXTERNAL');
  },

  /**
   * 判断错误是否可重试
   */
  isRetryable: (errorCode: SymbolMapperErrorCode): boolean => {
    if (SymbolMapperErrorCategories.isExternalError(errorCode)) {
      return !NON_RETRYABLE_EXTERNAL_CODES.has(errorCode);
    }
    if (SymbolMapperErrorCategories.isSystemError(errorCode)) {
      return RETRYABLE_SYSTEM_CODES.has(errorCode);
    }
    if (SymbolMapperErrorCategories.isBusinessError(errorCode)) {
      return RETRYABLE_BUSINESS_CODES.has(errorCode);
    }
    return false;
  },

  /**
   * 获取错误的恢复建议
   */
  getRecoveryAction: (errorCode: SymbolMapperErrorCode): 'retry' | 'fallback' | 'abort' => {
    if (SymbolMapperErrorCategories.isRetryable(errorCode)) {
      return 'retry';
    }

    if (SymbolMapperErrorCategories.isExternalError(errorCode) || SymbolMapperErrorCategories.isSystemError(errorCode)) {
      return 'fallback';
    }

    return 'abort';
  },

  /**
   * 获取错误严重级别
   */
  getSeverityLevel: (errorCode: SymbolMapperErrorCode): 'low' | 'medium' | 'high' | 'critical' => {
    if (SymbolMapperErrorCategories.isValidationError(errorCode)) {
      return 'low';
    }

    if (SymbolMapperErrorCategories.isBusinessError(errorCode)) {
      if (HIGH_SEVERITY_BUSINESS_ERRORS.has(errorCode)) {
        return 'high';
      }
      return 'medium';
    }

    if (SymbolMapperErrorCategories.isSystemError(errorCode)) {
      if (CRITICAL_SYSTEM_ERRORS.has(errorCode)) {
        return 'critical';
      }
      return 'high';
    }

    if (SymbolMapperErrorCategories.isExternalError(errorCode)) {
      if (CRITICAL_EXTERNAL_ERRORS.has(errorCode)) {
        return 'critical';
      }
      return 'high';
    }

    return 'medium';
  },

  /**
   * 判断是否需要清理缓存
   */
  requiresCacheCleanup: (errorCode: SymbolMapperErrorCode): boolean => {
    return CACHE_CLEANUP_ERRORS.has(errorCode);
  },

  /**
   * 判断是否需要重新加载规则
   */
  requiresRuleReload: (errorCode: SymbolMapperErrorCode): boolean => {
    return RULE_RELOAD_ERRORS.has(errorCode);
  },

  /**
   * 判断是否需要降级服务
   */
  requiresServiceDegradation: (errorCode: SymbolMapperErrorCode): boolean => {
    return SERVICE_DEGRADATION_ERRORS.has(errorCode);
  },

  /**
   * 判断是否需要立即告警
   */
  requiresImmediateAlert: (errorCode: SymbolMapperErrorCode): boolean => {
    return IMMEDIATE_ALERT_ERRORS.has(errorCode) || SymbolMapperErrorCategories.getSeverityLevel(errorCode) === 'critical';
  },
};

// 错误码说明映射（用于开发和调试）
export const SYMBOL_MAPPER_ERROR_DESCRIPTIONS = Object.freeze({
  [SYMBOL_MAPPER_ERROR_CODES.INVALID_SYMBOL_FORMAT]: 'Symbol format is invalid or malformed',
  [SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_NOT_FOUND]: 'Symbol mapping configuration not found',
  [SYMBOL_MAPPER_ERROR_CODES.MAPPING_CONFIG_ALREADY_EXISTS]: 'Symbol mapping configuration already exists',
  [SYMBOL_MAPPER_ERROR_CODES.DATA_SOURCE_NOT_FOUND]: 'Data source not found or not configured',
  [SYMBOL_MAPPER_ERROR_CODES.DATA_SOURCE_MAPPING_NOT_FOUND]: 'Data source mapping not found',
  [SYMBOL_MAPPER_ERROR_CODES.MAPPING_RULE_NOT_FOUND]: 'Mapping rule not found for specified criteria',
  [SYMBOL_MAPPER_ERROR_CODES.SYMBOL_MAPPING_FAILED]: 'Symbol mapping operation failed',
  [SYMBOL_MAPPER_ERROR_CODES.CACHE_OPERATION_FAILED]: 'Cache operation failed during symbol mapping',
  [SYMBOL_MAPPER_ERROR_CODES.DATABASE_CONNECTION_FAILED]: 'Failed to connect to symbol mapping database',
  [SYMBOL_MAPPER_ERROR_CODES.PROVIDER_API_UNAVAILABLE]: 'External symbol provider API is unavailable',
  [SYMBOL_MAPPER_ERROR_CODES.CIRCULAR_MAPPING_DETECTED]: 'Circular dependency detected in mapping rules',
  // 可根据需要添加更多描述
});