/**
 * Monitoring Component Error Codes
 *
 * Following the unified error handling system guidelines:
 * Format: {COMPONENT}_{CATEGORY}_{SEQUENCE}
 * Component: MONITORING
 * Categories: VALIDATION (001-299), BUSINESS (300-599), SYSTEM (600-899), EXTERNAL (900-999)
 */

export const MONITORING_ERROR_CODES = {
  // 验证类错误 (001-299) - Validation Errors
  CONFIG_VALIDATION_FAILED: 'MONITORING_VALIDATION_001',
  INVALID_CACHE_KEY_NAME: 'MONITORING_VALIDATION_002',
  EMPTY_CACHE_KEY_NAME: 'MONITORING_VALIDATION_003',
  INVALID_CACHE_KEY_CHARS: 'MONITORING_VALIDATION_004',
  CACHE_KEY_NAME_TOO_LONG: 'MONITORING_VALIDATION_005',
  INVALID_KEY_ARRAY: 'MONITORING_VALIDATION_006',
  UNSUPPORTED_CACHE_TYPE: 'MONITORING_VALIDATION_007',
  NEGATIVE_COMPRESSION_THRESHOLD: 'MONITORING_VALIDATION_008',
  INVALID_BATCH_SIZE: 'MONITORING_VALIDATION_009',
  INVALID_HIT_RATE_THRESHOLD: 'MONITORING_VALIDATION_010',
  INVALID_ERROR_RATE_THRESHOLD: 'MONITORING_VALIDATION_011',
  CORE_ENV_CONFIG_VALIDATION_FAILED: 'MONITORING_VALIDATION_012',
  ENHANCED_CONFIG_VALIDATION_FAILED: 'MONITORING_VALIDATION_013',

  // 业务逻辑错误 (300-599) - Business Logic Errors
  DATA_REQUEST_TIMEOUT: 'MONITORING_BUSINESS_300',
  DATA_UNAVAILABLE: 'MONITORING_BUSINESS_301',
  SERVICE_SHUTTING_DOWN: 'MONITORING_BUSINESS_302',
  ANALYZER_SHUTDOWN: 'MONITORING_BUSINESS_303',
  METRICS_COLLECTION_FAILED: 'MONITORING_BUSINESS_304',
  HEALTH_CHECK_FAILED: 'MONITORING_BUSINESS_305',
  SCORE_CALCULATION_FAILED: 'MONITORING_BUSINESS_306',
  TREND_ANALYSIS_FAILED: 'MONITORING_BUSINESS_307',
  PERFORMANCE_ANALYSIS_FAILED: 'MONITORING_BUSINESS_308',

  // 系统资源错误 (600-899) - System Resource Errors
  MEMORY_PRESSURE_HIGH: 'MONITORING_SYSTEM_600',
  CACHE_OPERATION_FAILED: 'MONITORING_SYSTEM_601',
  METRICS_REGISTRY_ERROR: 'MONITORING_SYSTEM_602',
  EVENT_BRIDGE_ERROR: 'MONITORING_SYSTEM_603',
  INTERCEPTOR_ERROR: 'MONITORING_SYSTEM_604',
  COLLECTOR_ERROR: 'MONITORING_SYSTEM_605',
  ANALYZER_ERROR: 'MONITORING_SYSTEM_606',
  PRESENTER_ERROR: 'MONITORING_SYSTEM_607',

  // 外部依赖错误 (900-999) - External Dependency Errors
  CACHE_SERVICE_UNAVAILABLE: 'MONITORING_EXTERNAL_900',
  DATABASE_CONNECTION_ERROR: 'MONITORING_EXTERNAL_901',
  METRICS_BACKEND_ERROR: 'MONITORING_EXTERNAL_902',
  EVENT_EMITTER_ERROR: 'MONITORING_EXTERNAL_903',
  CONFIG_SERVICE_ERROR: 'MONITORING_EXTERNAL_904',
  SERIALIZATION_ERROR: 'MONITORING_EXTERNAL_950',
  DESERIALIZATION_ERROR: 'MONITORING_EXTERNAL_951',
} as const;

export type MonitoringErrorCode = typeof MONITORING_ERROR_CODES[keyof typeof MONITORING_ERROR_CODES];