/**
 * Auth Component Error Codes
 *
 * Following unified error handling standards:
 * Format: AUTH_{CATEGORY}_{SEQUENCE}
 *
 * Categories:
 * - VALIDATION (001-299): Parameter validation, format validation, business rules validation
 * - BUSINESS (300-599): Business flow, status conflicts, resource not found
 * - SYSTEM (600-899): Memory/CPU, timeout, configuration errors
 * - EXTERNAL (900-999): Database, third-party API, network errors
 */
export const AUTH_ERROR_CODES = {
  // Validation Errors (001-299)
  INVALID_API_KEY_FORMAT: 'AUTH_VALIDATION_001',
  INVALID_CREDENTIALS: 'AUTH_VALIDATION_002',
  INVALID_TOKEN_FORMAT: 'AUTH_VALIDATION_003',
  INVALID_USER_ROLE: 'AUTH_VALIDATION_004',
  INVALID_PERMISSION_FORMAT: 'AUTH_VALIDATION_005',
  MISSING_REQUIRED_PARAMETERS: 'AUTH_VALIDATION_006',
  INVALID_PASSWORD_FORMAT: 'AUTH_VALIDATION_007',
  INVALID_EMAIL_FORMAT: 'AUTH_VALIDATION_008',
  RATE_LIMIT_EXCEEDED: 'AUTH_VALIDATION_010',

  // Business Logic Errors (300-599)
  API_KEY_NOT_FOUND: 'AUTH_BUSINESS_300',
  API_KEY_EXPIRED: 'AUTH_BUSINESS_301',
  API_KEY_REVOKED: 'AUTH_BUSINESS_302',
  USER_NOT_FOUND: 'AUTH_BUSINESS_303',
  USER_ACCOUNT_DISABLED: 'AUTH_BUSINESS_304',
  INSUFFICIENT_PERMISSIONS: 'AUTH_BUSINESS_305',
  SESSION_EXPIRED: 'AUTH_BUSINESS_306',
  TOKEN_EXPIRED: 'AUTH_BUSINESS_307',
  TOKEN_INVALID: 'AUTH_BUSINESS_308',
  MAX_API_KEYS_EXCEEDED: 'AUTH_BUSINESS_309',
  AUTHENTICATION_FAILED: 'AUTH_BUSINESS_310',
  AUTHORIZATION_FAILED: 'AUTH_BUSINESS_311',
  ACCOUNT_LOCKED: 'AUTH_BUSINESS_312',
  PASSWORD_POLICY_VIOLATION: 'AUTH_BUSINESS_313',
  DUPLICATE_API_KEY_NAME: 'AUTH_BUSINESS_314',

  // System Resource Errors (600-899)
  CACHE_SERVICE_UNAVAILABLE: 'AUTH_SYSTEM_600',
  CONFIGURATION_ERROR: 'AUTH_SYSTEM_601',
  SERVICE_INITIALIZATION_FAILED: 'AUTH_SYSTEM_602',
  RATE_LIMIT_SERVICE_ERROR: 'AUTH_SYSTEM_603',
  TOKEN_GENERATION_FAILED: 'AUTH_SYSTEM_700',
  ENCRYPTION_FAILED: 'AUTH_SYSTEM_701',
  PERFORMANCE_DEGRADATION: 'AUTH_SYSTEM_702',

  // External Dependency Errors (900-999)
  DATABASE_CONNECTION_FAILED: 'AUTH_EXTERNAL_900',
  DATABASE_QUERY_FAILED: 'AUTH_EXTERNAL_901',
  USER_REPOSITORY_ERROR: 'AUTH_EXTERNAL_902',
  API_KEY_REPOSITORY_ERROR: 'AUTH_EXTERNAL_903',
  EXTERNAL_AUTH_SERVICE_ERROR: 'AUTH_EXTERNAL_950',
  EXTERNAL_PERMISSION_SERVICE_ERROR: 'AUTH_EXTERNAL_951',
} as const;

export type AuthErrorCode = typeof AUTH_ERROR_CODES[keyof typeof AUTH_ERROR_CODES];