/**
 * Symbol Mapper Cache Error Codes
 *
 * Following unified error handling standards:
 * Format: SYMBOL_MAPPER_CACHE_{CATEGORY}_{SEQUENCE}
 *
 * Categories:
 * - VALIDATION (001-299): Parameter validation, format validation, business rules validation
 * - BUSINESS (300-599): Business flow, status conflicts, resource not found
 * - SYSTEM (600-899): Memory/CPU, timeout, configuration errors
 * - EXTERNAL (900-999): Database, third-party API, network errors
 */
export const SYMBOL_MAPPER_CACHE_ERROR_CODES = {
  // Validation Errors (001-299)
  INVALID_PROVIDER_FORMAT: 'SYMBOL_MAPPER_CACHE_VALIDATION_001',
  INVALID_SYMBOL_FORMAT: 'SYMBOL_MAPPER_CACHE_VALIDATION_002',
  INVALID_MAPPING_DIRECTION: 'SYMBOL_MAPPER_CACHE_VALIDATION_003',
  EMPTY_SYMBOL_ARRAY: 'SYMBOL_MAPPER_CACHE_VALIDATION_004',
  INVALID_CACHE_KEY: 'SYMBOL_MAPPER_CACHE_VALIDATION_005',

  // Business Logic Errors (300-599)
  MAPPING_NOT_FOUND: 'SYMBOL_MAPPER_CACHE_BUSINESS_300',
  CACHE_LAYER_UNAVAILABLE: 'SYMBOL_MAPPER_CACHE_BUSINESS_301',
  SYMBOL_MAPPING_FAILED: 'SYMBOL_MAPPER_CACHE_BUSINESS_302',
  BATCH_PROCESSING_FAILED: 'SYMBOL_MAPPER_CACHE_BUSINESS_303',
  PROVIDER_RULES_NOT_FOUND: 'SYMBOL_MAPPER_CACHE_BUSINESS_304',

  // System Resource Errors (600-899)
  MEMORY_PRESSURE: 'SYMBOL_MAPPER_CACHE_SYSTEM_600',
  CACHE_SIZE_LIMIT_EXCEEDED: 'SYMBOL_MAPPER_CACHE_SYSTEM_601',
  LRU_CLEANUP_FAILED: 'SYMBOL_MAPPER_CACHE_SYSTEM_602',
  MEMORY_MONITORING_FAILED: 'SYMBOL_MAPPER_CACHE_SYSTEM_603',
  CACHE_INITIALIZATION_FAILED: 'SYMBOL_MAPPER_CACHE_SYSTEM_700',
  OPERATION_TIMEOUT: 'SYMBOL_MAPPER_CACHE_SYSTEM_701',

  // External Dependency Errors (900-999)
  DATABASE_CONNECTION_FAILED: 'SYMBOL_MAPPER_CACHE_EXTERNAL_900',
  DATABASE_QUERY_FAILED: 'SYMBOL_MAPPER_CACHE_EXTERNAL_901',
  CHANGE_STREAM_FAILED: 'SYMBOL_MAPPER_CACHE_EXTERNAL_902',
  REPOSITORY_UNAVAILABLE: 'SYMBOL_MAPPER_CACHE_EXTERNAL_903',
  CHANGE_STREAM_RECONNECTION_FAILED: 'SYMBOL_MAPPER_CACHE_EXTERNAL_904',
} as const;

export type SymbolMapperCacheErrorCode = typeof SYMBOL_MAPPER_CACHE_ERROR_CODES[keyof typeof SYMBOL_MAPPER_CACHE_ERROR_CODES];