/**
 * Symbol Transformer Error Codes
 *
 * Following unified error handling standards:
 * Format: SYMBOL_TRANSFORMER_{CATEGORY}_{SEQUENCE}
 *
 * Categories:
 * - VALIDATION (001-299): Parameter validation, format validation, business rules validation
 * - BUSINESS (300-599): Business flow, status conflicts, resource not found
 * - SYSTEM (600-899): Memory/CPU, timeout, configuration errors
 * - EXTERNAL (900-999): Database, third-party API, network errors
 */
export const SYMBOL_TRANSFORMER_ERROR_CODES = {
  // Validation Errors (001-299)
  INVALID_PROVIDER_FORMAT: 'SYMBOL_TRANSFORMER_VALIDATION_001',
  EMPTY_SYMBOLS_ARRAY: 'SYMBOL_TRANSFORMER_VALIDATION_002',
  INVALID_DIRECTION_FORMAT: 'SYMBOL_TRANSFORMER_VALIDATION_003',
  SYMBOL_LENGTH_EXCEEDED: 'SYMBOL_TRANSFORMER_VALIDATION_004',
  BATCH_SIZE_EXCEEDED: 'SYMBOL_TRANSFORMER_VALIDATION_005',
  INVALID_SYMBOL_FORMAT: 'SYMBOL_TRANSFORMER_VALIDATION_006',
  SYMBOL_PATTERN_MISMATCH: 'SYMBOL_TRANSFORMER_VALIDATION_007',
  MISSING_REQUIRED_PARAMETERS: 'SYMBOL_TRANSFORMER_VALIDATION_008',

  // Business Logic Errors (300-599)
  SYMBOL_TRANSFORMATION_FAILED: 'SYMBOL_TRANSFORMER_BUSINESS_300',
  MAPPING_RULE_NOT_FOUND: 'SYMBOL_TRANSFORMER_BUSINESS_301',
  UNSUPPORTED_MARKET_TYPE: 'SYMBOL_TRANSFORMER_BUSINESS_302',
  TRANSFORMATION_PARTIALLY_FAILED: 'SYMBOL_TRANSFORMER_BUSINESS_303',
  SYMBOL_FORMAT_INCOMPATIBLE: 'SYMBOL_TRANSFORMER_BUSINESS_304',
  PROVIDER_NOT_SUPPORTED: 'SYMBOL_TRANSFORMER_BUSINESS_305',
  DUPLICATE_SYMBOL_REQUEST: 'SYMBOL_TRANSFORMER_BUSINESS_306',

  // System Resource Errors (600-899)
  CIRCUIT_BREAKER_OPEN: 'SYMBOL_TRANSFORMER_SYSTEM_600',
  OPERATION_TIMEOUT: 'SYMBOL_TRANSFORMER_SYSTEM_601',
  CACHE_SERVICE_UNAVAILABLE: 'SYMBOL_TRANSFORMER_SYSTEM_602',
  RETRY_ATTEMPTS_EXHAUSTED: 'SYMBOL_TRANSFORMER_SYSTEM_603',
  MEMORY_LIMIT_EXCEEDED: 'SYMBOL_TRANSFORMER_SYSTEM_604',
  PROCESSING_QUEUE_FULL: 'SYMBOL_TRANSFORMER_SYSTEM_605',
  PERFORMANCE_DEGRADATION: 'SYMBOL_TRANSFORMER_SYSTEM_700',
  RATE_LIMIT_EXCEEDED: 'SYMBOL_TRANSFORMER_SYSTEM_701',

  // External Dependency Errors (900-999)
  SYMBOL_MAPPER_CACHE_ERROR: 'SYMBOL_TRANSFORMER_EXTERNAL_900',
  EVENT_BUS_ERROR: 'SYMBOL_TRANSFORMER_EXTERNAL_901',
  MONITORING_SERVICE_ERROR: 'SYMBOL_TRANSFORMER_EXTERNAL_902',
  DATABASE_CONNECTION_ERROR: 'SYMBOL_TRANSFORMER_EXTERNAL_903',
  NETWORK_CONNECTIVITY_ERROR: 'SYMBOL_TRANSFORMER_EXTERNAL_950',
  EXTERNAL_SERVICE_TIMEOUT: 'SYMBOL_TRANSFORMER_EXTERNAL_951',
} as const;

export type SymbolTransformerErrorCode = typeof SYMBOL_TRANSFORMER_ERROR_CODES[keyof typeof SYMBOL_TRANSFORMER_ERROR_CODES];