#!/bin/bash

# 自动生成的目录结构修复脚本
# 请在执行前备份代码！

set -e

echo "开始修复目录结构..."

# 创建必要的目录
mkdir -p "src/app/config/module"
mkdir -p "src/app/config/validation/module"
mkdir -p "src/app/config/validation/services"
mkdir -p "src/app/modules/module"
mkdir -p "src/app/startup/module"
mkdir -p "src/app/startup/services"
mkdir -p "src/core/03-fetching/stream-data-fetcher/config/services"
mkdir -p "src/core/shared/types/enums"
mkdir -p "src/database/module"
mkdir -p "src/monitoring/analyzer/module"
mkdir -p "src/monitoring/analyzer/services"
mkdir -p "src/monitoring/cache/module"
mkdir -p "src/monitoring/cache/services"
mkdir -p "src/monitoring/collector/interceptors"
mkdir -p "src/monitoring/collector/module"
mkdir -p "src/monitoring/collector/repositories"
mkdir -p "src/monitoring/collector/services"
mkdir -p "src/monitoring/health/module"
mkdir -p "src/monitoring/health/services"
mkdir -p "src/monitoring/infrastructure/bridge/services"
mkdir -p "src/monitoring/infrastructure/metrics/constants"
mkdir -p "src/monitoring/infrastructure/metrics/module"
mkdir -p "src/monitoring/infrastructure/metrics/services"
mkdir -p "src/monitoring/infrastructure/module"
mkdir -p "src/monitoring/module"
mkdir -p "src/monitoring/presenter/controller"
mkdir -p "src/monitoring/presenter/module"
mkdir -p "src/monitoring/presenter/services"

# 移动文件到正确位置（跳过冲突文件）
echo "移动: app/config/config.module.ts -> app/config/module/config.module.ts"
mv "src/app/config/config.module.ts" "src/app/config/module/config.module.ts"
echo "移动: app/config/validation/config-validation.module.ts -> app/config/validation/module/config-validation.module.ts"
mv "src/app/config/validation/config-validation.module.ts" "src/app/config/validation/module/config-validation.module.ts"
echo "移动: app/config/validation/config-validator.service.ts -> app/config/validation/services/config-validator.service.ts"
mv "src/app/config/validation/config-validator.service.ts" "src/app/config/validation/services/config-validator.service.ts"
echo "移动: app/config/validation/dependencies-validator.service.ts -> app/config/validation/services/dependencies-validator.service.ts"
mv "src/app/config/validation/dependencies-validator.service.ts" "src/app/config/validation/services/dependencies-validator.service.ts"
echo "移动: app/config/validation/environment-validator.service.ts -> app/config/validation/services/environment-validator.service.ts"
mv "src/app/config/validation/environment-validator.service.ts" "src/app/config/validation/services/environment-validator.service.ts"
echo "移动: app/modules/app-core.module.ts -> app/modules/module/app-core.module.ts"
mv "src/app/modules/app-core.module.ts" "src/app/modules/module/app-core.module.ts"
echo "移动: app/modules/global-services.module.ts -> app/modules/module/global-services.module.ts"
mv "src/app/modules/global-services.module.ts" "src/app/modules/module/global-services.module.ts"
echo "移动: app/startup/graceful-shutdown.service.ts -> app/startup/services/graceful-shutdown.service.ts"
mv "src/app/startup/graceful-shutdown.service.ts" "src/app/startup/services/graceful-shutdown.service.ts"
echo "移动: app/startup/health-checker.service.ts -> app/startup/services/health-checker.service.ts"
mv "src/app/startup/health-checker.service.ts" "src/app/startup/services/health-checker.service.ts"
echo "移动: app/startup/startup.module.ts -> app/startup/module/startup.module.ts"
mv "src/app/startup/startup.module.ts" "src/app/startup/module/startup.module.ts"
echo "移动: core/03-fetching/stream-data-fetcher/config/stream-config.service.ts -> core/03-fetching/stream-data-fetcher/config/services/stream-config.service.ts"
mv "src/core/03-fetching/stream-data-fetcher/config/stream-config.service.ts" "src/core/03-fetching/stream-data-fetcher/config/services/stream-config.service.ts"
echo "移动: core/shared/types/storage-classification.enum.ts -> core/shared/types/enums/storage-classification.enum.ts"
mv "src/core/shared/types/storage-classification.enum.ts" "src/core/shared/types/enums/storage-classification.enum.ts"
echo "移动: database/database.module.ts -> database/module/database.module.ts"
mv "src/database/database.module.ts" "src/database/module/database.module.ts"
echo "移动: monitoring/analyzer/analyzer-health.service.ts -> monitoring/analyzer/services/analyzer-health.service.ts"
mv "src/monitoring/analyzer/analyzer-health.service.ts" "src/monitoring/analyzer/services/analyzer-health.service.ts"
echo "移动: monitoring/analyzer/analyzer-metrics.service.ts -> monitoring/analyzer/services/analyzer-metrics.service.ts"
mv "src/monitoring/analyzer/analyzer-metrics.service.ts" "src/monitoring/analyzer/services/analyzer-metrics.service.ts"
echo "移动: monitoring/analyzer/analyzer-score.service.ts -> monitoring/analyzer/services/analyzer-score.service.ts"
mv "src/monitoring/analyzer/analyzer-score.service.ts" "src/monitoring/analyzer/services/analyzer-score.service.ts"
echo "移动: monitoring/analyzer/analyzer-trend.service.ts -> monitoring/analyzer/services/analyzer-trend.service.ts"
mv "src/monitoring/analyzer/analyzer-trend.service.ts" "src/monitoring/analyzer/services/analyzer-trend.service.ts"
echo "移动: monitoring/analyzer/analyzer.module.ts -> monitoring/analyzer/module/analyzer.module.ts"
mv "src/monitoring/analyzer/analyzer.module.ts" "src/monitoring/analyzer/module/analyzer.module.ts"
echo "移动: monitoring/analyzer/analyzer.service.ts -> monitoring/analyzer/services/analyzer.service.ts"
mv "src/monitoring/analyzer/analyzer.service.ts" "src/monitoring/analyzer/services/analyzer.service.ts"
echo "移动: monitoring/cache/monitoring-cache.module.ts -> monitoring/cache/module/monitoring-cache.module.ts"
mv "src/monitoring/cache/monitoring-cache.module.ts" "src/monitoring/cache/module/monitoring-cache.module.ts"
echo "移动: monitoring/cache/monitoring-cache.service.ts -> monitoring/cache/services/monitoring-cache.service.ts"
mv "src/monitoring/cache/monitoring-cache.service.ts" "src/monitoring/cache/services/monitoring-cache.service.ts"
echo "移动: monitoring/collector/collector.interceptor.ts -> monitoring/collector/interceptors/collector.interceptor.ts"
mv "src/monitoring/collector/collector.interceptor.ts" "src/monitoring/collector/interceptors/collector.interceptor.ts"
echo "移动: monitoring/collector/collector.module.ts -> monitoring/collector/module/collector.module.ts"
mv "src/monitoring/collector/collector.module.ts" "src/monitoring/collector/module/collector.module.ts"
echo "移动: monitoring/collector/collector.repository.ts -> monitoring/collector/repositories/collector.repository.ts"
mv "src/monitoring/collector/collector.repository.ts" "src/monitoring/collector/repositories/collector.repository.ts"
echo "移动: monitoring/collector/collector.service.ts -> monitoring/collector/services/collector.service.ts"
mv "src/monitoring/collector/collector.service.ts" "src/monitoring/collector/services/collector.service.ts"
echo "移动: monitoring/health/extended-health.service.ts -> monitoring/health/services/extended-health.service.ts"
mv "src/monitoring/health/extended-health.service.ts" "src/monitoring/health/services/extended-health.service.ts"
echo "移动: monitoring/health/health.module.ts -> monitoring/health/module/health.module.ts"
mv "src/monitoring/health/health.module.ts" "src/monitoring/health/module/health.module.ts"
echo "移动: monitoring/infrastructure/bridge/monitoring-event-bridge.service.ts -> monitoring/infrastructure/bridge/services/monitoring-event-bridge.service.ts"
mv "src/monitoring/infrastructure/bridge/monitoring-event-bridge.service.ts" "src/monitoring/infrastructure/bridge/services/monitoring-event-bridge.service.ts"
echo "移动: monitoring/infrastructure/infrastructure.module.ts -> monitoring/infrastructure/module/infrastructure.module.ts"
mv "src/monitoring/infrastructure/infrastructure.module.ts" "src/monitoring/infrastructure/module/infrastructure.module.ts"
echo "移动: monitoring/infrastructure/metrics/metrics-registry.service.ts -> monitoring/infrastructure/metrics/services/metrics-registry.service.ts"
mv "src/monitoring/infrastructure/metrics/metrics-registry.service.ts" "src/monitoring/infrastructure/metrics/services/metrics-registry.service.ts"
echo "移动: monitoring/infrastructure/metrics/metrics.constants.ts -> monitoring/infrastructure/metrics/constants/metrics.constants.ts"
mv "src/monitoring/infrastructure/metrics/metrics.constants.ts" "src/monitoring/infrastructure/metrics/constants/metrics.constants.ts"
echo "移动: monitoring/infrastructure/metrics/metrics.module.ts -> monitoring/infrastructure/metrics/module/metrics.module.ts"
mv "src/monitoring/infrastructure/metrics/metrics.module.ts" "src/monitoring/infrastructure/metrics/module/metrics.module.ts"
echo "移动: monitoring/monitoring.module.ts -> monitoring/module/monitoring.module.ts"
mv "src/monitoring/monitoring.module.ts" "src/monitoring/module/monitoring.module.ts"
echo "移动: monitoring/presenter/presenter-error.service.ts -> monitoring/presenter/services/presenter-error.service.ts"
mv "src/monitoring/presenter/presenter-error.service.ts" "src/monitoring/presenter/services/presenter-error.service.ts"
echo "移动: monitoring/presenter/presenter.controller.ts -> monitoring/presenter/controller/presenter.controller.ts"
mv "src/monitoring/presenter/presenter.controller.ts" "src/monitoring/presenter/controller/presenter.controller.ts"
echo "移动: monitoring/presenter/presenter.module.ts -> monitoring/presenter/module/presenter.module.ts"
mv "src/monitoring/presenter/presenter.module.ts" "src/monitoring/presenter/module/presenter.module.ts"
echo "移动: monitoring/presenter/presenter.service.ts -> monitoring/presenter/services/presenter.service.ts"
mv "src/monitoring/presenter/presenter.service.ts" "src/monitoring/presenter/services/presenter.service.ts"

echo "目录结构修复完成！"
echo "正在清理空的 service 目录..."

# 清理空的 service 目录
find src -type d -name "service" -empty -delete 2>/dev/null || true
echo "已清理空的 service 目录"
echo "请检查并更新相关的导入语句"
echo "正在清理修复脚本..."

# 自焚命令 - 删除自己
SCRIPT_PATH="$0"
rm -f "$SCRIPT_PATH"
echo "修复脚本已自动删除"
