/**
 * Stream Receiver Component Error Codes
 *
 * Following the unified error handling system guidelines:
 * Format: {COMPONENT}_{CATEGORY}_{SEQUENCE}
 * Component: STREAM_RECEIVER
 * Categories: VALIDATION (001-299), BUSINESS (300-599), SYSTEM (600-899), EXTERNAL (900-999)
 */

export const STREAM_RECEIVER_ERROR_CODES = {
  // 验证类错误 (001-299) - Validation Errors
  INVALID_TIMESTAMP: 'STREAM_RECEIVER_VALIDATION_001',
  INVALID_AUTH_DATA: 'STREAM_RECEIVER_VALIDATION_002',
  MISSING_API_KEY: 'STREAM_RECEIVER_VALIDATION_003',
  MISSING_ACCESS_TOKEN: 'STREAM_RECEIVER_VALIDATION_004',
  DATA_VALIDATION_FAILED: 'STREAM_RECEIVER_VALIDATION_005',
  INVALID_SUBSCRIPTION_DATA: 'STREAM_RECEIVER_VALIDATION_006',
  INVALID_UNSUBSCRIBE_DATA: 'STREAM_RECEIVER_VALIDATION_007',
  RECOVERY_WINDOW_EXCEEDED: 'STREAM_RECEIVER_VALIDATION_008',

  // 业务逻辑错误 (300-599) - Business Logic Errors
  CONNECTION_RATE_EXCEEDED: 'STREAM_RECEIVER_BUSINESS_300',
  CONNECTION_LIMIT_REACHED: 'STREAM_RECEIVER_BUSINESS_301',
  AUTHENTICATION_FAILED: 'STREAM_RECEIVER_BUSINESS_302',
  INVALID_API_KEY: 'STREAM_RECEIVER_BUSINESS_303',
  INSUFFICIENT_PERMISSIONS: 'STREAM_RECEIVER_BUSINESS_304',
  SUBSCRIPTION_FAILED: 'STREAM_RECEIVER_BUSINESS_305',
  UNSUBSCRIBE_FAILED: 'STREAM_RECEIVER_BUSINESS_306',
  CLIENT_DISCONNECTED: 'STREAM_RECEIVER_BUSINESS_307',
  SUBSCRIPTION_NOT_FOUND: 'STREAM_RECEIVER_BUSINESS_308',
  RECOVERY_REQUEST_FAILED: 'STREAM_RECEIVER_BUSINESS_309',

  // 系统资源错误 (600-899) - System Resource Errors
  MEMORY_PRESSURE_HIGH: 'STREAM_RECEIVER_SYSTEM_600',
  CONNECTION_CLEANUP_FAILED: 'STREAM_RECEIVER_SYSTEM_601',
  WEBSOCKET_SERVER_ERROR: 'STREAM_RECEIVER_SYSTEM_602',
  RATE_LIMIT_SERVICE_ERROR: 'STREAM_RECEIVER_SYSTEM_603',
  CLIENT_STATE_MANAGER_ERROR: 'STREAM_RECEIVER_SYSTEM_604',
  BROADCAST_FAILED: 'STREAM_RECEIVER_SYSTEM_605',
  GATEWAY_INITIALIZATION_FAILED: 'STREAM_RECEIVER_SYSTEM_606',

  // 外部依赖错误 (900-999) - External Dependency Errors
  API_KEY_SERVICE_UNAVAILABLE: 'STREAM_RECEIVER_EXTERNAL_900',
  STREAM_SERVICE_ERROR: 'STREAM_RECEIVER_EXTERNAL_901',
  MONITORING_SERVICE_ERROR: 'STREAM_RECEIVER_EXTERNAL_902',
  EVENT_BUS_ERROR: 'STREAM_RECEIVER_EXTERNAL_903',
  RECOVERY_SERVICE_ERROR: 'STREAM_RECEIVER_EXTERNAL_950',
  NOTIFICATION_SERVICE_ERROR: 'STREAM_RECEIVER_EXTERNAL_951',
} as const;

export type StreamReceiverErrorCode = typeof STREAM_RECEIVER_ERROR_CODES[keyof typeof STREAM_RECEIVER_ERROR_CODES];